#!/bin/bash
# -*- coding: utf-8 -*-
# -*- mode: shell -*-

set -o nounset   # Fail when referencing undefined variables
set -o errexit   # Script exits on the first error
set -o pipefail  # Pipeline status failure if any command fails

user=$(whoami)

HADOOP_USER_NAME=hdfs hadoop fs -mkdir -p /user/$user
HADOOP_USER_NAME=hdfs hadoop fs -chown -R $user /user/$user
