/**
 * (c) Copyright 2012 WibiData, Inc.
 *
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.kiji.mapreduce;

import java.io.IOException;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.conf.Configured;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.hbase.TableNotFoundException;
import org.apache.hadoop.hbase.client.HTable;
import org.apache.hadoop.hbase.mapreduce.LoadIncrementalHFiles;

import org.kiji.annotations.ApiAudience;
import org.kiji.schema.InternalKijiError;
import org.kiji.schema.KijiTable;
import org.kiji.schema.impl.HBaseKijiTable;

/**
 * Loads HFiles generated from a bulk-import job into a Kiji table.
 *
 * @see org.kiji.mapreduce.KijiBulkImportJobBuilder
 * @see org.kiji.mapreduce.tools.KijiBulkLoad
 */
@ApiAudience.Public
public final class HFileLoader extends Configured {
  /**
   * Creates a new <code>HFileLoader</code> instance.
   *
   * @param conf The Hadoop configuration.
   */
  private HFileLoader(Configuration conf) {
    super(conf);
  }

  /**
   * Creates a new HFile loader.
   *
   * @param conf The configuration to be used by the new loader.
   * @return A new loader that can be used to add HFiles to HBase tables.
   */
  public static HFileLoader create(Configuration conf) {
    return new HFileLoader(conf);
  }

  /**
   * Loads HFiles directly into the regions of a Kiji table.
   *
   * @param hfilePath The path to the HFiles generated by a bulk-import job.
   * @param table The target kiji table.
   * @throws IOException If there is an error.
   */
  public void load(Path hfilePath, KijiTable table) throws IOException {
    try {
      LoadIncrementalHFiles loader = new LoadIncrementalHFiles(getConf());
      // doBulkLoad requires an actual HTable instance:
      loader.doBulkLoad(hfilePath, (HTable) HBaseKijiTable.downcast(table).getHTable());
    } catch (TableNotFoundException e) {
      throw new InternalKijiError("HBase table not found: " + e);
    } catch (Exception e) {
      throw new InternalKijiError("Couldn't create LoadIncrementalHFiles: " + e);
    }
  }
}
