#!/usr/bin/env python3
# -*- mode: python -*-
# -*- coding: utf-8 -*-

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""CLI interface to the KijiRest client.

Requires Python modules:
 - python-base
 - pyaml

Required modules can be installed with:
    $ pip install pyaml
"""

from base import base

from kiji.rest import kiji_rest


FLAGS = base.FLAGS


def Main(args):
  cli_handler = kiji_rest.KijiRestClientCLI(parent_flags=FLAGS)
  return cli_handler(args)


if __name__ == '__main__':
  base.Run(Main)
