#!/bin/bash

set -e

hostname=`hostname`

sed -i -e "s/\$BENTO_HOST/$hostname/" /etc/cassandra/conf.bento/*
sed -i -e "s/\$BENTO_HOST/$hostname/" /etc/hbase/conf.bento/*
sed -i -e "s/\$BENTO_HOST/$hostname/" /etc/hadoop/conf.bento/*
sed -i -e "s/\$BENTO_HOST/$hostname/" /etc/zookeeper/conf.bento/*

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
