#!/bin/bash
 #
 # (c) Copyright 2013 WibiData, Inc.
 #
 # See the NOTICE file distributed with this work for additional
 # information regarding copyright ownership.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
 #
 #     http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS,
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.

# Launches the kiji-scoring-server

cd $(dirname $0)/../
BASEDIR=$PWD

# attempt to find java (stolen from bigtop)
if [ -z "$JAVA_HOME" ]; then
  for candidate in \
    /usr/lib/jvm/java-6-sun \
    /usr/lib/jvm/java-1.6.0-sun-1.6.0.*/jre/ \
    /usr/lib/jvm/java-1.6.0-sun-1.6.0.* \
    /usr/lib/jvm/j2sdk1.6-oracle \
    /usr/lib/jvm/j2sdk1.6-oracle/jre \
    /usr/lib/j2sdk1.6-sun \
    /usr/java/jdk1.6* \
    /usr/java/jre1.6* \
    /Library/Java/Home \
    /usr/java/default \
    /usr/lib/jvm/default-java \
    /usr/lib/jvm/java-openjdk \
    /usr/lib/jvm/jre-openjdk \
    /usr/lib/jvm/java-1.6.0-openjdk-1.6.* \
    /usr/lib/jvm/jre-1.6.0-openjdk* ; do
    if [ -e $candidate/bin/java ]; then
      export JAVA_HOME=$candidate
      break
    fi
  done
fi

if [ -z "$JAVA_HOME" ]; then
  echo "$JAVA_HOME not set."
  exit 1
fi

if [ -z "$PIDFILE" ]; then
  PIDFILE=${BASEDIR}/kiji-scoring-server.pid
fi

kiji_jar=$(echo ${BASEDIR}/kiji-scoring-server*.jar)
scoring_server_cp="${kiji_jar}:${BASEDIR}/lib/*:${KIJI_CLASSPATH}"

# create logs directory
mkdir -p ${BASEDIR}/logs

${JAVA_HOME}/bin/java -cp ${scoring_server_cp} org.kiji.scoring.server.ScoringServer \
 > ${BASEDIR}/logs/console.out 2>&1 &

scoring_server_pid=$!

# check if the backgrounded process truly started
sleep 5
ps -p ${scoring_server_pid} > /dev/null
if [ 0 == $? ]; then
  echo ${scoring_server_pid} > $PIDFILE
else
  exit 1
fi


